replicaCount: 1

image:
  repository: medhavisingh12/kafka
  tag: consumer
  pullPolicy: Always

service:
  name: kafka-consumer
  type: ClusterIP
  port: 8080
  targetPort: 8080

kafka:
  brokerAddress: "localhost:9092"
  topic: "message-log"

resources: {}
scaledObject:
  enabled: true
  namespace: default
  targetDeployment: kafka-consumer
  minReplicaCount: 1
  maxReplicaCount: 5
  pollingInterval: 1
  cooldownPeriod: 100
  prometheus:
    serverAddress: http://prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090
    metricName: kafka_lag
    query: max(kafka_consumergroup_group_max_lag{group="my-group"})
    threshold: "20"